export const services = [
    {
        id: 1,
        title: 'Material Eléctrico',
        list: [
            'Cables',
            'Conectores',
            'Focos',
            'Lámparas de emergencia',
            'Luminarias led',
            'Luminarias suburbanas',
            'Reguladores',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'materialelectrico.webp',
    },{
        id: 2,
        title: 'Equipamiento deportivo',
        list: [
            'Bats',
            'Balones',
            'Canastas de Básquebotbol',
            'Cascos de futbol americano y equipó en general',
            'Manoplas',
            'Porterías',
            'Uniformes deportivos personalizados',
        ],
        image: 'equipodeportivo.webp',
    },{
        id: 3,
        title: 'Juguetes',
        list: [
            'Didacticos',
            'Escolares',
            'Niñas',
            'Niños',
            'Para bebés',
            'Preescolares',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'juguetes.webp',
    },{
        id: 4, 
        title: 'Herramientas y suministros',
        list: [
            'Clavos, tornillos',
            'Desarmadores',
            'Martillos',
            'Pinzas',
            'Taladros',
            'Toda clase de herramientas en general',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'herramientassuministros.webp',
    },{
        id: 5, 
        title: 'Tinacos',
        list: [
            'Cisternas de 1100 litros',
            'Tinacos de 450 litros',
            'Tinacos de 750 litros',
            'Tinacos de 1100 litros',
            'Trabajando con las mejores marcas del mercado',
            'Servicio de entrega en domicilio, solicitando la cotización correspondiente',
    
        ],
        image: 'tinacos.webp',
    },{
        id: 6, 
        title: 'Motos',
        list: [
            'Cuatrimotos',
            'Motos',
            'Servicio de balizamiento tipo moto patrulla',
            'Servicio de conversiones para entregas de comida rápida',
            'Servicio de conversiones para mensajería',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'motos.webp',
    },{
        id: 7, 
        title: 'Calentadores solares',
        list: [
            'Calentadores solares',
            'Diferentes capacidades para desde 3 personas a 18 personas',
            'Entrega a domicilio, solicitando la cotización correspondiente',
            'Gravedad',
            'Presición',
            'Servicio de instalacion a domicilio solicitando cotización respectiva por ubicación',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'calentadoressolares.webp',
    },{
        id: 8, 
        title: 'Tanques estacionarios',
        list: [
            'Diferentes capacidades de acuerdo a su necesidad',
            'Servicio de entrega a domicilio, solicitando la cotización correspondiente',
            'Servicio de instalación, solicitando cotización correspondiente en ubicación y área',
            'Tanques estacionarios',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'tanquesestacionarios.webp',
    },{
        id: 9, 
        title: 'Autos',
        list: [
            'Ambulancias',
            'Autos para aseguradoras',
            'Camionetas y camiones de carga',
            'Centros de atención de servicios de salud',
            'Flotillas',
            'Patrullas',
            'Servicios de balizamiento tipo moto patrulla',
            'Servicio de conversiones para ambulancias',
            'Servicio de conversiones de servicio de salud',
            'Servicio de conversiones para camionetas y camiones de carga',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'autos.webp',
    },{
        id: 10, 
        title: 'Bicicletas',
        list: [
            'Deportivas',
            'Infantiles',
            'Mensajería',
            'Para adulto',
            'Para servicios de:',
            'Policia',
            'Reparto de comida rápida',
            'Servicios de pintura y modificaciones',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'bici.webp',
    },{
        id: 11, 
        title: 'Despensas',
        list: [
            'Coorporativas',
            'Servicio de entregas a domicilio, solicitando la cotización correspondiente',
            'Sociales',
            'Trabajando con las mejores marcas del mercado',
        ],
        image: 'alimentos.webp',
    }
]
